services:

    stalwart:
        image: stalwartlabs/stalwart:latest
        container_name: stalwart
        hostname: mail.yourdomain.com    # change domain to your mail server  
        tty: true
        stdin_open: true
        ports:
            - 7443:443
            - 7080:8080
            - 25:25
            - 587:587
            - 465:465
            - 143:143
            - 993:993
            - 4190:4190
            - 110:110
            - 995:995
        volumes:
            - ./stalwart:/opt/stalwart
        restart: unless-stopped
        
    roundcube:
        image: roundcube/roundcubemail:latest
        container_name: roundcube
        restart: unless-stopped
        ports:
            - "680:80" 
        volumes:
            - ./roundcube/db:/var/roundcube/db
            - ./roundcube/config/:/var/roundcube/config/
        environment:
            - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.yourdomain.com  # change domain to your mail server
            - ROUNDCUBEMAIL_DEFAULT_PORT=993
            - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.yourdomain.com   #  change domain to your mail server
            - ROUNDCUBEMAIL_SMTP_PORT=465
            - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=50M
   
